# Generated by Django 3.2 on 2021-04-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auctions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auc_id', models.CharField(max_length=20)),
                ('auc_title', models.CharField(max_length=50)),
                ('auc_status', models.CharField(max_length=1)),
                ('cat_id', models.CharField(max_length=3)),
            ],
        ),
    ]
