# Generated by Django 3.2 on 2021-04-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auctions',
            name='id',
        ),
        migrations.AlterField(
            model_name='auctions',
            name='auc_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
