# Generated by Django 3.2 on 2021-05-23 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='category',
            field=models.ForeignKey(default='000000000000000', on_delete=django.db.models.deletion.CASCADE, to='auctions.category'),
        ),
    ]
