# Generated by Django 3.2 on 2021-05-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_alter_auction_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categ2',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('010000000000000', 'Books'), ('020000000000000', 'Films, Tv, Music & Games'), ('030000000000000', 'Electronics & Computers'), ('040000000000000', 'Home, Garden, Home Improvements and Pets'), ('050000000000000', 'Toys, Children & Baby')], default='010000000000000', max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='categ2',
            field=models.ForeignKey(blank=True, default='010000000000000', on_delete=django.db.models.deletion.CASCADE, to='auctions.categ2'),
        ),
    ]
