# Generated by Django 3.2 on 2021-05-30 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auto_20210530_1054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categ2',
            old_name='category',
            new_name='categ2',
        ),
    ]
