# Generated by Django 3.2 on 2021-06-10 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_rename_category_categ2_categ2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='categ2',
        ),
    ]
