# Generated by Django 3.2 on 2021-06-10 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_remove_auction_categ2'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='categ2',
            field=models.ForeignKey(blank=True, default='010000000000000', on_delete=django.db.models.deletion.CASCADE, to='auctions.categ2'),
        ),
    ]
